version: "3"

services:
  db:
    image: postgres:14
    container_name: music-map
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: music-map

volumes:
  db: